# Generated by Django 6.0.5 on 2026-05-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activity_level',
            field=models.CharField(choices=[('sedentary', 'Сидячий (без спорту)'), ('light', 'Легка (1-3 тренування)'), ('moderate', 'Середня (3-5 тренувань)'), ('active', 'Висока (щодня)')], default='light', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goal',
            field=models.CharField(choices=[('cut', 'Схуднення'), ('maintain', 'Підтримка'), ('bulk', 'Набір маси')], default='maintain', max_length=10),
        ),
    ]
