# Generated by Django 6.0.5 on 2026-05-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_profile_activity_level_alter_profile_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('gym', 'Тренажерний зал (Силове)'), ('streetball', 'Стрітбол/Баскетбол'), ('cardio', 'Кардіо (Біг/Велосипед)'), ('other', 'Інша активність (Ходьба)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='calories_burned',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
