# Generated by Django 6.0.5 on 2026-05-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_activitylog_activity_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Дата народження (YYYY-MM-DD)', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Чоловік'), ('F', 'Жінка')], default='M', max_length=1),
        ),
    ]
