# Generated by Django 6.0.5 on 2026-05-08 11:10

import django.utils.timezone
import tracker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_activitylog_date_alter_bodymetriclog_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='bodymetriclog',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='foodlog',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, validators=[tracker.models.validate_birth_date]),
        ),
        migrations.AlterField(
            model_name='waterlog',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
